#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Nov  5 10:31:17 2025

@author: christophermontesdeoca
"""
#TO DO

#create a function 

#Create an output that tells the user if the currency abbreviation they input was correct 

#the ability to insert the actual name of the currency as well as the symbol 

# Define the problem you are trying to solve. - Problem being solved is the conversion of currency from one origin currency to a different one
#How does your program help to solve the problem? - The program will translate any given currency from one to another

#Who will be the users of this program. Detail at least two Use Cases a. Use Case 1 b. Use Case 2"""- Case A would be a user planning out their-
#travel to another country and that user would like to know how much of that currency they would need to convert to have a supple amount for their trip and to have a general idea. 
#Case B would be for a user that is at a currency exchange booth, and that user would like to know if they are truly getting their moneys worth of that exchange and to make sure the booth isnt pulling - 
#a fast one on them.

#What technology is available to solve the problem? Identify the specific APIs and Modules to be used for the program. - The API we will be using for this would be a currency exchange API which translates - 
#currency that is given to it and will translate it to whatever target currency the user wants.

#Detail the sequence of the program- What is the flow of the program? How does a user use the program. The sequence would be, the user is asked for their native currency for example USD and then they will- 
#be asked to input the new currency they want


import http.client
import requests
import sys

currency_list = { 
    'USD':"US Dollar", 
    'ARS':"Argentine Peso",
    'BBD':"Barbados Dollar",
    'BSD':"Bahamian Dollar",
    'PYG':"Paraguat Guarani",
    'PAB':"Panamanian Balboa",
    'BRL':"Brazilian Real",
   "BMD": "Bermudian Dollar",
    "BOB": "Bolivian Boliviano",
    "BZD": "Belize Dollar",
    "XCD": "East Caribbean Dollar",
    "DOP": "Dominican Peso",
    "COP": "Colombian Peso",
    "CRC": "Costa Rican Colon",
    "CUP": "Cuban Peso",
    "HTG": "Haitian Gourde",
    "ANG": "Netherlands Antillian Guilder",
    "HNL": "Honduran Lempira",
    "CAD": "Canadian Dollar",
    "KYD": "Cayman Islands Dollar",
    "PEN": "Peruvian Sol",
    "MXN": "Mexican Peso",
    "NIO": "Nicaraguan Cordoba Oro",
    "TTD": "Trinidad and Tobago Dollar",
    "GTQ": "Guatemalan Quetzal",
    "VES": "Venezuelan Bolivar",
    "UYU": "Uruguay Peso",
    "JMD": "Jamaican Dollar",
    "CLP": "Chilean Peso",
    "AUD": "Australian Dollar",
    "MOP": "Macau Pataca",
    "PKR": "Pakistan Rupee",
    "PHP": "Philippine Peso",
    "FJD": "Fiji Dollar",
    "HKD": "Hong Kong Dollar",
    "KRW": "Korean Won",
    "KHR": "Cambodian Riel",
    "LAK": "Lao Kip",
    "MYR": "Malaysian Ringgit",
    "BDT": "Bangladeshi Taka",
    "MMK": "Myanmar Kyat",
    "NPR": "Nepalese Rupee",
    "CNY": "Chinese Yuan Renminbi",
    "JPY": "Japanese Yen",
    "SCR": "Seychelles Rupee",
    "LKR": "Sri Lanka Rupee",
    "XPF": "CFP Franc",
    "THB": "Thai Baht",
    "BND": "Brunei Dollar",
    "SGD": "Singapore Dollar",
    "TWD": "Taiwan Dollar",
    "NZD": "New Zealand Dollar",
    "INR": "Indian Rupee",
    "IDR": "Indonesian Rupiah",
    "VND": "Vietnamese Dong",
    "ALL": "Albanian Lek",
    "BYN": "Belarusian Ruble",
    "BGN": "Bulgarian Lev",
    "ISK": "Iceland Krona",
    "PLN": "Polish Zloty",
    "DKK": "Danish Krone",
    "RUB": "Russian Ruble",
    "CZK": "Czech Koruna",
    "HRK": "Croatian Kuna",
    "RON": "Romanian Leu",
    "MKD": "Macedonia Denar",
    "MDL": "Moldovan Leu",
    "NOK": "Norwegian Krone",
    "EUR": "Euro",
    "SEK": "Swedish Krona",
    "CHF": "Swiss Franc",
    "RSD": "Serbian Dinar",
    "UAH": "Ukraine Hryvnia",
    "HUF": "Hungarian Forint",
    "GBP": "British Pound",
    "AED": "United Arab Emirates Dirham",
    "OMR": "Omani Rial",
    "AZN": "Azerbaijani Manat",
    "BHD": "Bahraini Dinar",
    "GEL": "Georgian Lari",
    "KZT": "Kazakhstan Tenge",
    "KGS": "Kyrgyzstani Som",
    "QAR": "Qatari Rial",
    "KWD": "Kuwaiti Dinar",
    "LBP": "Lebanese Pound",
    "SAR": "Saudi Riyal",
    "TRY": "Turkish Lira",
    "TMT": "Turkmenistan Manat",
    "UZS": "Uzbekistan Som",
    "AMD": "Armenian Dram",
    "YER": "Yemeni Rial",
    "IQD": "Iraqi Dinar",
    "IRR": "Iranian Rial",
    "ILS": "Israeli New Shekel",
    "JOD": "Jordanian Dinar",
    "DZD": "Algerian Dinar",
    "EGP": "Egyptian Pound",
    "ETB": "Ethiopian Birr",
    "AOA": "Angolan Kwanza",
    "BWP": "Botswana Pula",
    "BIF": "Burundi Franc",
    "XOF": "CFA BCEAO Franc",
    "CVE": "Cape Verde Escudo",
    "GMD": "Gambian Dalasi",
    "DJF": "Djibouti Franc",
    "GNF": "Guinea Franc",
    "GHS": "Ghanaian Cedi",
    "KES": "Kenyan Shilling",
    "LSL": "Lesotho Loti",
    "LYD": "Libyan Dinar",
    "RWF": "Rwanda Franc",
    "MWK": "Malawi Kwacha",
    "MUR": "Mauritius Rupee",
    "MAD": "Moroccan Dirham",
    "NAD": "Namibian Dollar",
    "ZAR": "South African Rand",
    "NGN": "Nigerian Naira",
    "SZL": "Swaziland Lilangeni",
    "SDG": "Sudanese Pound",
    "SOS": "Somali Shilling",
    "TZS": "Tanzanian Shilling",
    "TND": "Tunisian Dinar",
    "UGX": "Uganda Shilling",
    "ZMW": "Zambian Kwacha",
    "XAF": "CFA BEAC Franc",
    "BAM": "Bosnia and Herzegovina Marka",
    "SYP": "Syrian Pound" }

while True: 
    
    user = input("Welcome to the currency exchange program! \n \nPlease select one of the options listed below. \n 1.) Convert Currency. \n 2.) Find an interesting vacation spot. \n 3.) Quit \n ")
  
   
    if user == "3" :
        print("Have a great day!")
        sys.exit()
       
       
    elif user == "1": 
        while True:

            base = input("Please enter your native currency (EX- USD, CAD, EUR...):  ").upper()   
            print("") 
            break

        Response1 = (input(f"The currency you have selected is {base}, is this correct?: ")).lower() 
        print("")
       
        if base not in currency_list:
            print("The currency you have selected is not available try again. \n") 
           
        if Response1 == ("yes"):
            break
            
        elif Response1 == ("no"): 
            print("Please try again \n ---------------")  
        
        else: 
            print("Please enter either input yes or no. \n")  
    
while True: 
    
    target = input("Please enter the currency you would like to translate to: ").upper()
    print(" ")
    Response2 = (input(f"The currency you have selected to translate is {target}, is that right?:  "))  
    print("")
    
    
    if target not in currency_list:
        print("The currency you have selected is not available")
    if Response2 == ("yes"):
        break
        
    elif Response2 == ("no"): 
        print("Please try again \n ---------------")  
        
    else: 
        print("Please enter either yes or no ")     


while True:  
    try:
        amount = float(input(f"please enter how much {base} you would like to convert to {target}: ")) 
        break
    except ValueError: 
        print("please enter a valid number please: \n ")
        
        
        Response3 =(input("The amount you you entered was {amount}, is this right?: ")).lower()   #Gives the user a chance to verify the currency they have selected. 
    
    
    if Response3 == ("yes"):
        break
        
    elif Response3 == ("no"): 
        print("Please try again \n ---------------")  
        
    else: 
        print("Please enter either yes or no ")    
        

querystring = {"base": base, "target": target, "amount": amount} 

conn = http.client.HTTPSConnection("exchange-rates7.p.rapidapi.com")

headers = {
    'x-rapidapi-key': "b584caf4bbmshfa91dbc98b0d996p18d32bjsnac2d0472099a",
    'x-rapidapi-host': "exchange-rates7.p.rapidapi.com"
}

conn.request("GET", "/codes", headers=headers)  

res = conn.getresponse()

data = res.read()




url = "https://exchange-rates7.p.rapidapi.com/convert"

    


headers = {
	"x-rapidapi-key": "1fbd89b6admsh452592d91c1e41cp1ac476jsn4233e9f07bea",
	"x-rapidapi-host": "exchange-rates7.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

results = response.json()


rate = float(results["convert_result"]["rate"])   



print("-------------------------------------------------------")

print(f"base currency is: {base}")

print(" ")

print(f"Target is: {target} ")

print(" ")

print(f"Conversion rate from {base} to {target} is: {rate}") 

print(" ")

calculated_answer = float(amount * rate)

print(f"{amount} {base} is {calculated_answer} {target}") 


#now just need to filter out if the user types in a variable that is not real in this case using (if mot in )
 
        
    
